## Assignment 2
2.	Classify the email using the binary classification method. Email Spam detection has two states: a) Normal State – Not Spam, b) Abnormal State – Spam. Use K-Nearest Neighbors and Support Vector Machine for classification. Analyze their performance.
Dataset link: The emails.csv dataset on the Kaggle https://www.kaggle.com/datasets/balaka18/email-spam-classification-dataset-csv



In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
# import warnings
# warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
df=pd.read_csv('emails.csv')

In [3]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [4]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [5]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [6]:
df.dropna(inplace = True)

In [7]:
df.drop(['Email No.'],axis=1,inplace=True)
X = df.drop(['Prediction'],axis = 1)
y = df['Prediction']

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
# split into train and test


In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [10]:
X_train = scaler.fit_transform(X_train)
X_train

array([[0.03333333, 0.03603604, 0.00293255, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.04285714, 0.04504505, 0.00293255, ..., 0.        , 0.01754386,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00952381, 0.0990991 , 0.        , ..., 0.        , 0.02631579,
        0.        ],
       [0.01428571, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [11]:
X_test = scaler.transform(X_test)
X_test

array([[0.0047619 , 0.00900901, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.06190476, 0.18018018, 0.19061584, ..., 0.        , 0.        ,
        0.        ],
       [0.0047619 , 0.12612613, 0.0058651 , ..., 0.        , 0.04385965,
        0.        ],
       ...,
       [0.00952381, 0.00900901, 0.00879765, ..., 0.        , 0.        ,
        0.        ],
       [0.00952381, 0.01801802, 0.00293255, ..., 0.        , 0.        ,
        0.        ],
       [0.0047619 , 0.00900901, 0.        , ..., 0.        , 0.        ,
        0.        ]])

##KNN classifier

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
 
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [13]:
print("Prediction",y_pred)

Prediction [0 0 1 ... 0 1 1]


In [14]:
print("KNN accuracy = ",metrics.accuracy_score(y_test,y_pred))

KNN accuracy =  0.821520618556701


In [15]:
print("Confusion matrix",metrics.confusion_matrix(y_test,y_pred))

Confusion matrix [[833 264]
 [ 13 442]]


## SVM classifier

In [ ]:
from sklearn.svm import SVC

In [16]:
# cost C = 1
model = SVC(C = 5)

# fit
model.fit(X_train, y_train)

# predict
y_pred = model.predict(X_test)

In [17]:
metrics.confusion_matrix(y_true=y_test, y_pred=y_pred)

array([[1087,   10],
       [  76,  379]])

In [18]:
print("SVM accuracy = ",metrics.accuracy_score(y_test,y_pred))

SVM accuracy =  0.9445876288659794
